; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.1-alpha on 2025-11-23 at 09:06:41
; total layer number: 1
; filament_density: 1.25
; filament_diameter: 1.75
; max_z_height: 0.20
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 144x144 1616
; iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAEgklEQVR4Ae3c6U3rTBTG8ZEQm9gCYh
; MQCFtEICwlpARKoAQ6oARKoARKoARKSAkpgeujq0ghOIljj+1zZv4/6fnyLleK4zs+k2dk5wAAAAAA
; AAAAAAAAAAAAAAAAAABAj4ODg7e9vb3XhYWFhgOyWl1dfWq329+Pj48/ksvLyy/5Zw6YRVac4Y0zmm
; 63O5B/54A08phqNpsfaTfPaGQ14pGGX+Tx1Ol0+rNuntHVaGtr69kBR0dH71lvnPHI/8tqFKnxQTlv
; 5M9gwI7MpEE5b4YDNqtR4OQLbrVanz5vnvEBe2lpqeUQnvX19Z6sFGXdPKOr0c7OzotDOIoMynkjPw
; nwSDNu3u2578iAzXbfKN+DcpFHGgO2IfJFyTCr4eYZDQO2ATK8artx0lYjB32y9FiaViMeaUrUPSgX
; WY0YsGsmB74s3TRpoU+rga8eS0vo0yqkZXvuOwzYJSu7x9IStvslqKrH0rQaMWB7UkePpSX0aQVY3Z
; 77jgzYsgI7ZBfqoJw39GkZae2xtIQBewrtPZaWcGAthaUeS0vkJ43oH2kMysUi1y7a7X4IPZaGyCNN
; rmU0q1FoPZaWRPECCLbn5SbYPi3riwuInwS13WdQridB9Gkx91haYvLAGoOyrpg6sMagrDPq+7RYDn
; xZj8oBO7YDX9ajqk9jULabWg+ssT0PI7W8AIIeK6xUNmDL8MX2PNyUOmBz4CuOlNKn0WPFFy8vgGBQ
; jjuF+jS252SYufo0eiySlkx9GoMymZaZA/ba2lrv5uZmYOUDkWpzd3f3k6xCvamr0PLy8tPJycnHw8
; ODqQ9Hys3Z2Znsylouq+Rx9prccQMrH5CUE1lIGo1Gvt+FZDW6uLj4tvJhid/Id7+4uFj8INr+/v47
; j7S4kvSd784nWY0YsMPP7e3tYOagXMTx8TEDdqA5PT39clXY2Nh4ljvVyoUh0yPb883NzRdXJXmkJX
; fsp5WLRNIj23Mvg3JeMmCz3bcXGUOSX5X9Dsp5yWp0fX3dt3QBY45shlZWVnpOm6S1ZcBWnmazWc2g
; nJf0aZ1OZ2DlgsaSTD2WFvRpujJ3j6UFfVq9kb/AyXfw5iyT1ejq6qpv6cKHkHa7PUiufc+Fgj6tuh
; weHn64ECVbR/q0EmNqUM5LDmfTp/mP9FgmB+W86NP8RFad3Ae+rKNPK5baeywtZMC+v7839eXVGXn8
; ez/wZZ2sRsnWs2/pi6wjpR/4so4Be3LU91haMGD/Ti0HvqyjT/sfsz2WFrH2afIXZ3d313aPpUVsB9
; bUHviyLoYDa/IZHcojrxgJsU+LosfSIvn1tRXSgB1dj6VF0gG9WB6wu91uvD2WFlb7tPPzc3osTSwd
; WKPHUkp7n0aPZYTGPo0eyxgtfRo9lmHDAbuu1YgDX4Go+gUQql5cAD+q6tPosQJXZp/GoBwJ3y9Up8
; eKkK8Daxz4ilzeA2ty421vb9NjYf4XQMh/y/Ycf2Tp04J9cQH8mPRCdQZlzGW0T6vsBdwIi/Rp9FgA
; AAAAAAAAAAAAAAAAAAAAAAAAlPkH1PKxsuQHUJ0AAAAASUVORK5CYII=
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.42mm
; top infill extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=Cube_8_id_0_copy_0 CENTER=217.732,39.0256 POLYGON=[[192.732,14.0256],[242.732,14.0256],[242.732,64.0256],[192.732,64.0256],[192.732,14.0256]]
M106 S0
M106 P2 S0
;TYPE:Custom
;;===== date: 20240520 =====================
;printer_model:Elegoo Centauri Carbon
;initial_filament:PLA
;curr_bed_type:Textured PEI Plate
;Target chamber temp for print is 0

M400 ; wait for buffer to clear
M8213
M400
M220 S100 ;Set the feed speed to 100%
M221 S100 ;Set the flow rate to 100%

M104 S140
M140 S60

G90
G28 ;home
M729 ;Clean Nozzle



M204 S5000 ;Call exterior wall print acceleration


M190 S60
M109 S210
M83
G92 E0 ;Reset Extruder

SET_PRINT_STATS_INFO TOTAL_LAYER=1
;LAYER_COUNT:1
;LAYER:0
G90
G21
M83 ; use relative distances for extrusion
; filament start gcode
M106 P3 S200


M106 P2 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.2
G92 E0
;
;
;
;
;
;
G1 E-.8 F1800
;LAYER:1
SET_PRINT_STATS_INFO CURRENT_LAYER=1

;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=500
EXCLUDE_OBJECT_START NAME=Cube_8_id_0_copy_0
G1 X242.382 Y63.676 F30000
G1 Z.6
G1 Z.2
G1 E.8 F1800
;TYPE:Outer wall
;WIDTH:0.5
G1 F3000
G1 X193.082 Y63.676 E1.79876
G1 X193.082 Y14.376 E1.79876
G1 X242.382 Y14.376 E1.79876
G1 X242.382 Y63.636 E1.7973
G1 E-.728 F1800
;WIPE_START
G1 F30000
G1 X241.182 Y63.637 E-.072
;WIPE_END
G1 X241.336 Y56.006 Z.6
G1 X242.154 Y15.53 Z.6
G1 Z.2
G1 E.8 F1800
;TYPE:Bottom surface
;WIDTH:0.500793
G1 F6300
G1 X241.434 Y14.81 E.03721
G1 X240.786 Y14.81 E.02367
G1 X241.948 Y15.972 E.06005
G1 X241.948 Y16.619 E.02367
G1 X240.138 Y14.81 E.09352
G1 X239.491 Y14.81 E.02367
G1 X241.948 Y17.267 E.12699
G1 X241.948 Y17.914 E.02367
G1 X238.843 Y14.81 E.16046
G1 X238.196 Y14.81 E.02367
G1 X241.948 Y18.562 E.19393
G1 X241.948 Y19.209 E.02367
G1 X237.548 Y14.81 E.2274
G1 X236.901 Y14.81 E.02367
G1 X241.948 Y19.857 E.26087
G1 X241.948 Y20.504 E.02367
G1 X236.253 Y14.81 E.29434
G1 X235.606 Y14.81 E.02367
G1 X241.948 Y21.152 E.32781
G1 X241.948 Y21.799 E.02367
G1 X234.958 Y14.81 E.36128
G1 X234.311 Y14.81 E.02367
G1 X241.948 Y22.447 E.39475
G1 X241.948 Y23.094 E.02367
G1 X233.663 Y14.81 E.42822
G1 X233.016 Y14.81 E.02367
G1 X241.948 Y23.742 E.46169
G1 X241.948 Y24.39 E.02367
G1 X232.368 Y14.81 E.49516
G1 X231.721 Y14.81 E.02367
G1 X241.948 Y25.037 E.52863
G1 X241.948 Y25.685 E.02367
G1 X231.073 Y14.81 E.5621
G1 X230.426 Y14.81 E.02367
G1 X241.948 Y26.332 E.59557
G1 X241.948 Y26.98 E.02367
G1 X229.778 Y14.81 E.62904
G1 X229.13 Y14.81 E.02367
G1 X241.948 Y27.627 E.66251
G1 X241.948 Y28.275 E.02367
G1 X228.483 Y14.81 E.69598
G1 X227.835 Y14.81 E.02367
G1 X241.948 Y28.922 E.72945
G1 X241.948 Y29.57 E.02367
G1 X227.188 Y14.81 E.76292
G1 X226.54 Y14.81 E.02367
G1 X241.948 Y30.217 E.79639
G1 X241.948 Y30.865 E.02367
G1 X225.893 Y14.81 E.82986
G1 X225.245 Y14.81 E.02367
G1 X241.948 Y31.512 E.86333
G1 X241.948 Y32.16 E.02367
G1 X224.598 Y14.81 E.8968
G1 X223.95 Y14.81 E.02367
G1 X241.948 Y32.807 E.93027
G1 X241.948 Y33.455 E.02367
G1 X223.303 Y14.81 E.96374
G1 X222.655 Y14.81 E.02367
G1 X241.948 Y34.103 E.99721
G1 X241.948 Y34.75 E.02367
G1 X222.008 Y14.81 E1.03068
G1 X221.36 Y14.81 E.02367
G1 X241.948 Y35.398 E1.06415
G1 X241.948 Y36.045 E.02367
G1 X220.713 Y14.81 E1.09762
G1 X220.065 Y14.81 E.02367
G1 X241.948 Y36.693 E1.13109
G1 X241.948 Y37.34 E.02367
G1 X219.418 Y14.81 E1.16456
G1 X218.77 Y14.81 E.02367
G1 X241.948 Y37.988 E1.19803
G1 X241.948 Y38.635 E.02367
G1 X218.122 Y14.81 E1.2315
G1 X217.475 Y14.81 E.02367
G1 X241.948 Y39.283 E1.26497
G1 X241.948 Y39.93 E.02367
G1 X216.827 Y14.81 E1.29844
G1 X216.18 Y14.81 E.02367
G1 X241.948 Y40.578 E1.33191
G1 X241.948 Y41.225 E.02367
G1 X215.532 Y14.81 E1.36538
G1 X214.885 Y14.81 E.02367
G1 X241.948 Y41.873 E1.39885
G1 X241.948 Y42.52 E.02367
G1 X214.237 Y14.81 E1.43232
G1 X213.59 Y14.81 E.02367
G1 X241.948 Y43.168 E1.46579
G1 X241.948 Y43.815 E.02367
G1 X212.942 Y14.81 E1.49926
G1 X212.295 Y14.81 E.02367
G1 X241.948 Y44.463 E1.53273
G1 X241.948 Y45.111 E.02367
G1 X211.647 Y14.81 E1.5662
G1 X211 Y14.81 E.02367
G1 X241.948 Y45.758 E1.59967
G1 X241.948 Y46.406 E.02367
G1 X210.352 Y14.81 E1.63314
G1 X209.705 Y14.81 E.02367
G1 X241.948 Y47.053 E1.66661
G1 X241.948 Y47.701 E.02367
G1 X209.057 Y14.81 E1.70008
G1 X208.409 Y14.81 E.02367
G1 X241.948 Y48.348 E1.73355
G1 X241.948 Y48.996 E.02367
G1 X207.762 Y14.81 E1.76702
G1 X207.114 Y14.81 E.02367
G1 X241.948 Y49.643 E1.80049
G1 X241.948 Y50.291 E.02367
G1 X206.467 Y14.81 E1.83396
G1 X205.819 Y14.81 E.02367
G1 X241.948 Y50.938 E1.86743
G1 X241.948 Y51.586 E.02367
G1 X205.172 Y14.81 E1.9009
G1 X204.524 Y14.81 E.02367
G1 X241.948 Y52.233 E1.93437
G1 X241.948 Y52.881 E.02367
G1 X203.877 Y14.81 E1.96784
G1 X203.229 Y14.81 E.02367
G1 X241.948 Y53.528 E2.00131
G1 X241.948 Y54.176 E.02367
G1 X202.582 Y14.81 E2.03478
G1 X201.934 Y14.81 E.02367
G1 X241.948 Y54.823 E2.06825
G1 X241.948 Y55.471 E.02367
G1 X201.287 Y14.81 E2.10172
G1 X200.639 Y14.81 E.02367
G1 X241.948 Y56.119 E2.13519
G1 X241.948 Y56.766 E.02367
G1 X199.992 Y14.81 E2.16866
G1 X199.344 Y14.81 E.02367
G1 X241.948 Y57.414 E2.20213
G1 X241.948 Y58.061 E.02367
G1 X198.697 Y14.81 E2.2356
G1 X198.049 Y14.81 E.02367
G1 X241.948 Y58.709 E2.26907
G1 X241.948 Y59.356 E.02367
G1 X197.401 Y14.81 E2.30254
G1 X196.754 Y14.81 E.02367
G1 X241.948 Y60.004 E2.33601
G1 X241.948 Y60.651 E.02367
G1 X196.106 Y14.81 E2.36948
G1 X195.459 Y14.81 E.02367
G1 X241.948 Y61.299 E2.40295
G1 X241.948 Y61.946 E.02367
G1 X194.811 Y14.81 E2.43642
G1 X194.164 Y14.81 E.02367
G1 X241.948 Y62.594 E2.46989
G1 X241.948 Y63.241 E.02367
G1 X193.516 Y14.81 E2.50336
G1 X193.516 Y15.457 E.02367
G1 X241.3 Y63.241 E2.46989
G1 X240.653 Y63.241 E.02367
G1 X193.516 Y16.105 E2.43642
G1 X193.516 Y16.752 E.02367
G1 X240.005 Y63.241 E2.40295
G1 X239.358 Y63.241 E.02367
G1 X193.516 Y17.4 E2.36948
G1 X193.516 Y18.047 E.02367
G1 X238.71 Y63.241 E2.33601
G1 X238.063 Y63.241 E.02367
G1 X193.516 Y18.695 E2.30254
G1 X193.516 Y19.343 E.02367
G1 X237.415 Y63.241 E2.26907
G1 X236.768 Y63.241 E.02367
G1 X193.516 Y19.99 E2.2356
G1 X193.516 Y20.638 E.02367
G1 X236.12 Y63.241 E2.20213
G1 X235.473 Y63.241 E.02367
G1 X193.516 Y21.285 E2.16866
G1 X193.516 Y21.933 E.02367
G1 X234.825 Y63.241 E2.13519
G1 X234.177 Y63.241 E.02367
G1 X193.516 Y22.58 E2.10172
G1 X193.516 Y23.228 E.02367
G1 X233.53 Y63.241 E2.06825
G1 X232.882 Y63.241 E.02367
G1 X193.516 Y23.875 E2.03478
G1 X193.516 Y24.523 E.02367
G1 X232.235 Y63.241 E2.00131
G1 X231.587 Y63.241 E.02367
G1 X193.516 Y25.17 E1.96784
G1 X193.516 Y25.818 E.02367
G1 X230.94 Y63.241 E1.93437
G1 X230.292 Y63.241 E.02367
G1 X193.516 Y26.465 E1.9009
G1 X193.516 Y27.113 E.02367
G1 X229.645 Y63.241 E1.86743
G1 X228.997 Y63.241 E.02367
G1 X193.516 Y27.76 E1.83396
G1 X193.516 Y28.408 E.02367
G1 X228.35 Y63.241 E1.80049
G1 X227.702 Y63.241 E.02367
G1 X193.516 Y29.055 E1.76702
G1 X193.516 Y29.703 E.02367
G1 X227.055 Y63.241 E1.73355
G1 X226.407 Y63.241 E.02367
G1 X193.516 Y30.351 E1.70008
G1 X193.516 Y30.998 E.02367
G1 X225.76 Y63.241 E1.66661
G1 X225.112 Y63.241 E.02367
G1 X193.516 Y31.646 E1.63314
G1 X193.516 Y32.293 E.02367
G1 X224.465 Y63.241 E1.59967
G1 X223.817 Y63.241 E.02367
G1 X193.516 Y32.941 E1.5662
G1 X193.516 Y33.588 E.02367
G1 X223.169 Y63.241 E1.53273
G1 X222.522 Y63.241 E.02367
G1 X193.516 Y34.236 E1.49926
G1 X193.516 Y34.883 E.02367
G1 X221.874 Y63.241 E1.46579
G1 X221.227 Y63.241 E.02367
G1 X193.516 Y35.531 E1.43232
G1 X193.516 Y36.178 E.02367
G1 X220.579 Y63.241 E1.39885
G1 X219.932 Y63.241 E.02367
G1 X193.516 Y36.826 E1.36538
G1 X193.516 Y37.473 E.02367
G1 X219.284 Y63.241 E1.33191
G1 X218.637 Y63.241 E.02367
G1 X193.516 Y38.121 E1.29844
G1 X193.516 Y38.768 E.02367
G1 X217.989 Y63.241 E1.26497
G1 X217.342 Y63.241 E.02367
G1 X193.516 Y39.416 E1.2315
G1 X193.516 Y40.064 E.02367
G1 X216.694 Y63.241 E1.19803
G1 X216.047 Y63.241 E.02367
G1 X193.516 Y40.711 E1.16456
G1 X193.516 Y41.359 E.02367
G1 X215.399 Y63.241 E1.13109
G1 X214.752 Y63.241 E.02367
G1 X193.516 Y42.006 E1.09762
G1 X193.516 Y42.654 E.02367
G1 X214.104 Y63.241 E1.06415
G1 X213.457 Y63.241 E.02367
G1 X193.516 Y43.301 E1.03068
G1 X193.516 Y43.949 E.02367
G1 X212.809 Y63.241 E.99721
G1 X212.161 Y63.241 E.02367
G1 X193.516 Y44.596 E.96374
G1 X193.516 Y45.244 E.02367
G1 X211.514 Y63.241 E.93027
G1 X210.866 Y63.241 E.02367
G1 X193.516 Y45.891 E.8968
G1 X193.516 Y46.539 E.02367
G1 X210.219 Y63.241 E.86333
G1 X209.571 Y63.241 E.02367
G1 X193.516 Y47.186 E.82986
G1 X193.516 Y47.834 E.02367
G1 X208.924 Y63.241 E.79639
G1 X208.276 Y63.241 E.02367
G1 X193.516 Y48.481 E.76292
G1 X193.516 Y49.129 E.02367
G1 X207.629 Y63.241 E.72945
G1 X206.981 Y63.241 E.02367
G1 X193.516 Y49.776 E.69599
G1 X193.516 Y50.424 E.02367
G1 X206.334 Y63.241 E.66252
G1 X205.686 Y63.241 E.02367
G1 X193.516 Y51.072 E.62905
G1 X193.516 Y51.719 E.02367
G1 X205.039 Y63.241 E.59558
G1 X204.391 Y63.241 E.02367
G1 X193.516 Y52.367 E.56211
G1 X193.516 Y53.014 E.02367
G1 X203.744 Y63.241 E.52864
G1 X203.096 Y63.241 E.02367
G1 X193.516 Y53.662 E.49517
G1 X193.516 Y54.309 E.02367
G1 X202.449 Y63.241 E.4617
G1 X201.801 Y63.241 E.02367
G1 X193.516 Y54.957 E.42823
G1 X193.516 Y55.604 E.02367
G1 X201.153 Y63.241 E.39476
G1 X200.506 Y63.241 E.02367
G1 X193.516 Y56.252 E.36129
G1 X193.516 Y56.899 E.02367
G1 X199.858 Y63.241 E.32782
G1 X199.211 Y63.241 E.02367
G1 X193.516 Y57.547 E.29435
G1 X193.516 Y58.194 E.02367
G1 X198.563 Y63.241 E.26088
G1 X197.916 Y63.241 E.02367
G1 X193.516 Y58.842 E.22741
G1 X193.516 Y59.489 E.02367
G1 X197.268 Y63.241 E.19394
G1 X196.621 Y63.241 E.02367
G1 X193.516 Y60.137 E.16047
G1 X193.516 Y60.784 E.02367
G1 X195.973 Y63.241 E.127
G1 X195.326 Y63.241 E.02367
G1 X193.516 Y61.432 E.09353
G1 X193.516 Y62.08 E.02367
G1 X194.678 Y63.241 E.06006
G1 X194.031 Y63.241 E.02367
G1 X193.311 Y62.521 E.03722
G1 E-.728 F1800
;WIPE_START
G1 F30000
G1 X194.031 Y63.241 E-.0611
G1 X194.212 Y63.241 E-.0109
;WIPE_END
EXCLUDE_OBJECT_END NAME=Cube_8_id_0_copy_0
M106 S0
M106 P2 S0
;TYPE:Custom
; filament end gcode 
;===== date: 20250109 =====================
M400 ; wait for buffer to clear
M140 S0 ;Turn-off bed
M106 S255 ;Cooling nozzle
M83
G92 E0 ; zero the extruder
G2 I1 J0 Z0.7 E-1 F3000 ; lower z a little
G90
G1 Z100 F20000 ; Move print head up 
M204 S5000
M400
M83
G1 X202 F20000
M400
G1 Y250 F20000
G1 Y264.5 F1200
M400
G92 E0
M104 S0 ;Turn-off hotend
M140 S0 ;Turn-off bed
M106 S0 ; turn off fan
M106 P2 S0 ; turn off remote part cooling fan
M106 P3 S0 ; turn off chamber cooling fan
M84 ;Disable all steppers
; EXECUTABLE_BLOCK_END

; filament used [mm] = 196.96
; filament used [cm3] = 0.47
; filament used [g] = 0.59
; total filament used [g] = 0.59
; total filament cost = 0.00
; total layers count = 1
; estimated printing time (normal mode) = 1m 33s
; estimated first layer printing time (normal mode) = 1s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 0
; accel_to_decel_factor = 50%
; activate_air_filtration = 0
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0
; adaptive_pressure_advance_bridges = 0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0
; additional_cooling_fan_speed = 0
; align_infill_direction_to_model = 0
; alternate_extra_wall = 0
; auxiliary_fan = 1
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 246x0,256x0,256x20,246x20
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n;{if layer_num >= full_fan_speed_layer[current_extruder]}\n;{if filament_type[initial_no_support_extruder]==\"ASA\"}\n;M106 P3 S100\n;{endif}\n;{endif}\n;{if layer_num >= full_fan_speed_layer[current_extruder]}\n;{if filament_type[initial_no_support_extruder]==\"ABS\"}\n;M106 P3 S100\n;{endif}\n;{endif}
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 5
; bottom_shell_thickness = 0.6
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_density = 100%
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_no_support = 0
; bridge_speed = 50
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = no_brim
; brim_width = 5
; calib_flowrate_topinfill_special_order = 0
; chamber_temperature = 0
; change_extrusion_role_gcode = 
; change_filament_gcode = M600
; close_fan_the_first_x_layers = 1
; complete_print_exhaust_fan_speed = 70
; cool_plate_temp = 35
; cool_plate_temp_initial_layer = 35
; cooling_tube_length = 5
; cooling_tube_retraction = 90
; counterbore_hole_bridging = none
; curr_bed_type = Textured PEI Plate
; default_acceleration = 10000
; default_bed_type = 4
; default_filament_colour = ""
; default_filament_profile = "Elegoo PLA @ECC"
; default_jerk = 0
; default_junction_deviation = 0
; default_print_profile = 0.20mm Standard @Elegoo CC 0.4 nozzle
; deretraction_speed = 30
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = brim_type;filament_flow_ratio;overhang_fan_threshold;before_layer_change_gcode;host_type;layer_change_gcode;machine_start_gcode;print_host
; disable_m73 = 1
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 0
; draft_shield = disabled
; during_print_exhaust_fan_speed = 70
; elefant_foot_compensation = 0.1
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 1
; enable_extra_bridge_layer = disabled
; enable_filament_ramming = 0
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 0
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 0
; eng_plate_temp_initial_layer = 0
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 1
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height_to_lid = 90
; extruder_clearance_height_to_rod = 36
; extruder_clearance_radius = 57
; extruder_colour = #000000
; extruder_offset = 0x0
; extrusion_rate_smoothing_external_perimeter_only = 0
; fan_cooling_layer_time = 80
; fan_kickstart = 0
; fan_max_speed = 100
; fan_min_speed = 50
; fan_speedup_overhangs = 1
; fan_speedup_time = 0.5
; filament_colour = #000000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 1.25
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode \n"
; filament_flow_ratio = 0.96
; filament_ids = EPLAB00
; filament_is_support = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 21
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "My Elegoo PLA"
; filament_shrink = 100%
; filament_shrinkage_compensation_z = 100%
; filament_soluble = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 0
; filament_start_gcode = "; filament start gcode\n{if  (bed_temperature[current_extruder] >55)||(bed_temperature_initial_layer[current_extruder] >55)}M106 P3 S200\n{elsif(bed_temperature[current_extruder] >50)||(bed_temperature_initial_layer[current_extruder] >50)}M106 P3 S150\n{elsif(bed_temperature[current_extruder] >45)||(bed_temperature_initial_layer[current_extruder] >45)}M106 P3 S50\n{endif}\n\n{if activate_air_filtration[current_extruder] && support_air_filtration}\nM106 P3 S{during_print_exhaust_fan_speed_num[current_extruder]} \n{endif}"
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Elegoo
; filename_format = ECC_{nozzle_diameter[0]}_{input_filename_base}_{filament_type[0]}{layer_height}_{print_time}.gcode
; fill_multiline = 1
; filter_out_gap_fill = 1
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 1
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_mode = displacement
; fuzzy_skin_noise_type = classic
; fuzzy_skin_octaves = 4
; fuzzy_skin_persistence = 0.5
; fuzzy_skin_point_distance = 0.3
; fuzzy_skin_scale = 1
; fuzzy_skin_thickness = 0.2
; gap_fill_target = everywhere
; gap_infill_speed = 250
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 0
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = elegoolink
; hot_plate_temp = 60
; hot_plate_temp_initial_layer = 60
; idle_temperature = 0
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 40
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 45
; infill_jerk = 9
; infill_lock_depth = 1
; infill_overhang_angle = 60
; infill_shift_step = 0.4
; infill_wall_overlap = 15%
; inherits_group = ;"Elegoo PLA @ECC";"Elegoo Centauri Carbon 0.4 nozzle"
; initial_layer_acceleration = 500
; initial_layer_infill_speed = 105
; initial_layer_jerk = 9
; initial_layer_line_width = 0.5
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 50
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 0
; inner_wall_jerk = 9
; inner_wall_line_width = 0.45
; inner_wall_speed = 200
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_angle = 0
; internal_bridge_density = 100%
; internal_bridge_fan_speed = -1
; internal_bridge_flow = 0.95
; internal_bridge_speed = 150%
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.42
; internal_solid_infill_pattern = monotonic
; internal_solid_infill_speed = 250
; ironing_angle = -1
; ironing_fan_speed = -1
; ironing_flow = 10%
; ironing_inset = 0
; ironing_pattern = rectilinear
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; is_infill_first = 0
; lateral_lattice_angle_1 = -45
; lateral_lattice_angle_2 = 45
; layer_change_gcode = ;LAYER:{layer_num+1}\nSET_PRINT_STATS_INFO CURRENT_LAYER={layer_num + 1}\n
; layer_height = 0.2
; line_width = 0.42
; long_retractions_when_cut = 0
; machine_end_gcode = ;===== date: 20250109 =====================\nM400 ; wait for buffer to clear\nM140 S0 ;Turn-off bed\nM106 S255 ;Cooling nozzle\nM83\nG92 E0 ; zero the extruder\nG2 I1 J0 Z{max_layer_z+0.5} E-1 F3000 ; lower z a little\nG90\n{if max_layer_z > 50}G1 Z{min(max_layer_z+50, printable_height+0.5)} F20000{else}G1 Z100 F20000 {endif}; Move print head up \nM204 S5000\nM400\nM83\nG1 X202 F20000\nM400\nG1 Y250 F20000\nG1 Y264.5 F1200\nM400\nG92 E0\nM104 S0 ;Turn-off hotend\nM140 S0 ;Turn-off bed\nM106 S0 ; turn off fan\nM106 P2 S0 ; turn off remote part cooling fan\nM106 P3 S0 ; turn off chamber cooling fan\nM84 ;Disable all steppers
; machine_load_filament_time = 29
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 20000,20000
; machine_max_acceleration_retracting = 5000,5000
; machine_max_acceleration_travel = 20000,20000
; machine_max_acceleration_x = 20000,20000
; machine_max_acceleration_y = 20000,20000
; machine_max_acceleration_z = 500,200
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 9,9
; machine_max_jerk_y = 9,9
; machine_max_jerk_z = 3,3
; machine_max_junction_deviation = 0,0
; machine_max_speed_e = 30,30
; machine_max_speed_x = 500,200
; machine_max_speed_y = 500,200
; machine_max_speed_z = 20,20
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = M600
; machine_start_gcode = ;;===== date: 20240520 =====================\n;printer_model:[printer_model]\n;initial_filament:{filament_type[initial_extruder]}\n;curr_bed_type:{curr_bed_type}\n;Target chamber temp for print is [overall_chamber_temperature]\n\nM400 ; wait for buffer to clear\nM8213\nM400\nM220 S100 ;Set the feed speed to 100%\nM221 S100 ;Set the flow rate to 100%\n\nM104 S140\nM140 S60\n\nG90\nG28 ;home\nM729 ;Clean Nozzle\n\n\n{if enable_pressure_advance[initial_extruder] == \"true\"}\nSET_PRESSURE_ADVANCE ADVANCE=[pressure_advance]\nM400\n{endif}\nM204 S{min(20000,max(1000,outer_wall_acceleration))} ;Call exterior wall print acceleration\n\n\nM190 S[bed_temperature_initial_layer_single]\nM109 S[nozzle_temperature_initial_layer]\nM83\nG92 E0 ;Reset Extruder\n\nSET_PRINT_STATS_INFO TOTAL_LAYER=[total_layer_count]\n;LAYER_COUNT:[total_layer_count]\n;LAYER:0
; machine_tool_change_time = 0
; machine_unload_filament_time = 28
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 1
; max_bridge_length = 10
; max_layer_height = 0.28
; max_resonance_avoidance_speed = 120
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; min_length_factor = 0.5
; min_resonance_avoidance_speed = 70
; min_skirt_length = 0
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 15
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 210
; nozzle_temperature_initial_layer = 210
; nozzle_temperature_range_high = 240
; nozzle_temperature_range_low = 190
; nozzle_type = hardened_steel
; nozzle_volume = 107
; only_one_wall_first_layer = 0
; only_one_wall_top = 1
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 5000
; outer_wall_jerk = 9
; outer_wall_line_width = 0.42
; outer_wall_speed = 120
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 100
; overhang_fan_threshold = 25%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; parking_pos_retraction = 90
; pellet_flow_coefficient = 0.4157
; pellet_modded_printer = 0
; post_process = 
; precise_outer_wall = 0
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.024
; prime_tower_brim_width = 3
; prime_tower_width = 35
; prime_volume = 45
; print_compatible_printers = "Elegoo Centauri Carbon 0.4 nozzle"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = 0.20mm Strength @Elegoo CC 0.4 nozzle
; printable_area = 0x0,257x0,257x257,0x257
; printable_height = 257
; printer_model = Elegoo Centauri Carbon
; printer_notes = 
; printer_settings_id = My Elegoo Centauri Carbon 0.4 nozzle - DELTANOPURGE
; printer_structure = corexy
; printer_technology = FFF
; printer_variant = 0.4
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 0
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 1
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 3
; resolution = 0.012
; resonance_avoidance = 0
; retract_before_wipe = 0%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 255
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_length = 0.8
; retraction_minimum_travel = 0.8
; retraction_speed = 30
; role_based_wipe_speed = 0
; scan_first_layer = 1
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 10%
; seam_position = aligned
; seam_slope_conditional = 1
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 1
; seam_slope_min_length = 0
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 0
; single_loop_draft_shield = 0
; skeleton_infill_density = 25%
; skeleton_infill_line_width = 100%
; skin_infill_density = 25%
; skin_infill_depth = 2
; skin_infill_line_width = 100%
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 0
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 4
; slow_down_layers = 0
; slow_down_min_speed = 20
; slowdown_for_curled_perimeters = 0
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_direction = 45
; solid_infill_filament = 1
; solid_infill_rotate_template = 0,90
; sparse_infill_acceleration = 100%
; sparse_infill_density = 20%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = rectilinear
; sparse_infill_rotate_template = 0,90
; sparse_infill_speed = 200
; spiral_finishing_flow_ratio = 0
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; spiral_starting_flow_ratio = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; supertack_plate_temp = 35
; supertack_plate_temp_initial_layer = 35
; support_air_filtration = 0
; support_angle = 0
; support_base_pattern = default
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 0
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_ironing = 0
; support_ironing_flow = 10%
; support_ironing_pattern = rectilinear
; support_ironing_spacing = 0.1
; support_line_width = 0.42
; support_material_interface_fan_speed = -1
; support_multi_bed_types = 0
; support_object_first_layer_gap = 0.2
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_threshold_overlap = 50%
; support_top_z_distance = 0.2
; support_type = normal(auto)
; symmetric_infill_y_axis = 0
; temperature_vitrification = 45
; template_custom_gcode = 
; textured_cool_plate_temp = 40
; textured_cool_plate_temp_initial_layer = 40
; textured_plate_temp = 60
; textured_plate_temp_initial_layer = 60
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 144x144/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 5%
; top_shell_layers = 6
; top_shell_thickness = 1
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 2000
; top_surface_density = 100%
; top_surface_jerk = 9
; top_surface_line_width = 0.42
; top_surface_pattern = monotonicline
; top_surface_speed = 200
; travel_acceleration = 0
; travel_jerk = 12
; travel_slope = 3
; travel_speed = 500
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 30
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_angle_organic = 45
; tree_support_branch_diameter = 2
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 5
; tree_support_brim_width = 3
; tree_support_tip_diameter = 2
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = classic
; wall_loops = 6
; wall_sequence = inner-outer-inner wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 1.2
; wipe_on_loops = 0
; wipe_speed = 100%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 30
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_rib_length = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_fillet_wall = 1
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rib_width = 8
; wipe_tower_rotation_angle = 0
; wipe_tower_wall_type = rectangle
; wipe_tower_x = 165.000
; wipe_tower_x = 165,165
; wipe_tower_y = 250.000
; wipe_tower_y = 250,250
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Auto Lift
; z_offset = 0
; first_layer_bed_temperature = 60
; bed_shape = 0x0,257x0,257x257,0x257
; first_layer_temperature = 210
; first_layer_height = 0.200
; CONFIG_BLOCK_END


